apiVersion: batch/v1
kind: Job
metadata:
  name: pytest-runner
spec:
  template:
    spec:
      containers:
        - name: pytest
          image: mayezra/my_flask_api:main 
          command: ["pytest"]
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST
              value: "flask-app-postgresql"
            - name: POSTGRES_DB
              value: "students"
            - name: CACHE_REDIS_HOST
              value: "flask-app-redis-master"
            - name: CACHE_REDIS_PORT
              value: "6379"
            - name: CACHE_REDIS_DB
              value: "0"
      restartPolicy: Never
  backoffLimit: 0
