name: Build and Push Docker Image

# Trigger the workflow on push
on:
  push:
    branches: "main"
  # Optionally trigger on pull requests
  pull_request:
    branches: [ "main", "master" ]

# Environment variables
env:
  DOCKER_IMAGE: mayezra/my_flask_api
  DOCKER_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository code to the runner
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Set up Docker Buildx for advanced building features
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Extract metadata for tags and labels
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix=sha-
          type=raw,value=latest,enable={{is_default_branch}}
    
    # Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # build in this path
        file: ./Dockerfile
        push: true # Push to registry after building
        tags: ${{ steps.meta.outputs.tags }} 
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha # Use GitHub Actions cache for faster builds
        cache-to: type=gha,mode=max # Save cache layers for next build